#!/bin/sh

# Script for downloading the plugings for my neovim setup

echo "Welcome to the auto-plugins-installer"
echo

function plugs {

	if [[ "$(which git)" ]]; then
		
		mkdir bundle
		cd bundle
		git clone https://github.com/VundleVim/Vundle.vim/
		cd ../

        git clone https://github.com/itchyny/lightline.vim

		echo "nvim +PluginInstall +qall"
	else
		echo "Please install git!" && echo && exit 1
	fi

}


if [[ ! -d bundle && ! -d nerdtree && ! -d emmet-vim && ! -d vim-airline && ! -d vim-airline-themes ]]; then

	read -rp "Would you like to download the plugins? [yes/no]: " download
	echo

	if [[ $download == "yes" ]]; then
		$(plugs)
	else
		echo "Exiting..." && echo && exit 1
	fi
else
	echo "Plugins are already installed"
	echo
	read -rp "Would you like to redownload the plugins? [yes/no]: " redownload
	echo

	if [[ $redownload == "yes" ]]; then
		rm -rf bundle lightline.vim
		$(plugs)
	else
		echo "Exiting..." && echo && exit 1
	fi
fi

